todo_app/config/routes.rb
Rails.application.routes.draw do

	get 'todos/informes'
	resources :todos
	get 'todos/:id/completado', to: 'todos#completado', as:'completado'
    root 'todos#index'


end

todo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo_app/app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

todo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

todo_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :find_todo, only: [:show, :edit, :update, :destroy, :completado]

	def index
		@todos = Todo.all
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def new
 		@todo = Todo.new
 	end

 	def create
 		@todo = Todo.new(todo_params)
 		@todo.save
 		redirect_to todos_path
 	end

 	def destroy
 		@todo = Todo.find(params[:id])
 		@todo.destroy
 		redirect_to todos_path
 	end

 	
 	def edit
 		@todo = Todo.find(params[:id])
 	end

 	def update
 		@todo = Todo.find(params[:id])
 		@todo.update(todo_params)
 		redirect_to todos_path
 	end

 	def completado
 		@todo.completed = true
    	@todo.save
    	redirect_to todos_path
 	end

 	def informes

 	end

 	private

 	def todo_params
 		params.require(:todo).permit(:description, :completed)
 	end

	def find_todo
    	@todo = Todo.find(params[:id])
  	end
end

todo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_app/app/helpers/todos_helper.rb
module TodosHelper
end

todo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <!-- CDN BOOTSTRAP!-->


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'menu' %>
    <%= yield %>
  </body>
</html>

todo_app/app/views/todos/_form.html.erb
<%= form_with(model: @todo, local: true) do |f| %>
 <%= f.label :title, "Description" %>
 <%= f.text_area :description %>
 <%= f.label :estado, "Completed" %>
 <%= f.check_box :completed%>
 <%= f.submit "GRABAR" %>
 <%= link_to 'Back', todos_path , class:'btn btn-danger' %>
<% end %>

todo_app/app/views/todos/_list.html.erb
  <% if @todos.any? %>
     <% @todos.each do |todo| %>
      <div class="well">
        <h2> <%= todo.description %> </h2>
        <%= todo.completed%>
        <%= link_to 'Show', todo, class:'btn btn-primary' %>
        <%= link_to 'Edit', edit_todo_path(todo), class:'btn btn-primary' %>
        <%= link_to 'Destroy', todo, class:'btn btn-primary', method: :delete, data: { confirm: 'Esta Seguro de eliminar' } %>
        <%= link_to 'Completar', completado_path(todo), class:'btn btn-primary' %>
       </div> 
      <% end %>
  <% else %>
      <h1>No existen Registros</h1>
      <%= link_to 'Nuevo', new_todo_path %>
  <% end %>

todo_app/app/views/todos/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top">
<div class="container">
  <ul class="nav navbar-nav">
	<li class="btn btn-default"><a href="<%= root_path %>">HOME</a></li>
	<li class="btn btn-default"><a href="<%= new_todo_path %>">NUEVO</a></li>
	<li class="btn btn-default"><a href="<%= todos_informes_path %>">LISTA</a></li>
   </ul>
</div>
</nav>

todo_app/app/views/todos/edit.html.erb
<h1>Editar</h1>
<%= render 'form', todo: @todo %>

todo_app/app/views/todos/index.html.erb
<h1> Index.html </h1>
<%= render 'list' %>

todo_app/app/views/todos/informes.html.erb
informes.html.erb

todo_app/app/views/todos/new.html.erb
<h1>Nuevo</h1>
<%= render 'form', todo: @todo %>

todo_app/app/views/todos/show.html.erb
<p>
  <strong>Contenido:</strong>
  <%= @todo.description %>
  <strong>Estado:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo), class:'btn btn-primary' %>|
<%= link_to 'Back', todos_path , class:'btn btn-danger' %>